[package]
name = "canflow-tests"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
canflow-types = { workspace = true }
canflow-bus = { workspace = true }
canflow-adapter = { workspace = true }
canflow-analysis = { workspace = true }
canflow-agent = { workspace = true }
tokio = { workspace = true }
rand = { workspace = true }
serde_json = { workspace = true }

[[test]]
name = "integration"
path = "tests/integration.rs"

[[test]]
name = "throughput"
path = "tests/throughput.rs"

[[test]]
name = "vcan"
path = "tests/vcan.rs"
